name: Manually Deploy to Heroku

on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: "9e57503c-f968-4a04-b193-6b468d4eea23"
          heroku_email: "farshadsafari206@gmail.com"
          heroku_app_name: "taggeracc2" #Must be unique in Heroku
