name: Manually Deploy to Heroku

on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: "39f3f995-3544-451a-83aa-4f30f8626477"
          heroku_email: "ferifarshad46@gmail.com"
          heroku_app_name: "testselff" #Must be unique in Heroku
